In [2]:
import numpy as np
matrix=np.random.randint(1,101,(5,5))
print(matrix)

[[24 76 25 36 32]
 [10 76 28 71 33]
 [18 76 73 80 40]
 [17 80  7 12 52]
 [31 96 90  4 36]]


In [10]:
ematrix=matrix%2==0
sqrlmatrix=matrix.astype(float)
sqrlmatrix[ematrix]=np.sqrt(sqrlmatrix[ematrix])
print(sqrlmatrix)

[[ True  True False  True  True]
 [ True  True  True False False]
 [ True  True False  True  True]
 [False  True False  True  True]
 [False  True  True  True  True]]
[[ 4.89897949  8.71779789 25.          6.          5.65685425]
 [ 3.16227766  8.71779789  5.29150262 71.         33.        ]
 [ 4.24264069  8.71779789 73.          8.94427191  6.32455532]
 [17.          8.94427191  7.          3.46410162  7.21110255]
 [31.          9.79795897  9.48683298  2.          6.        ]]


In [15]:
x=np.linspace(-3,3,50)
print(x)
sigmoid=1/(1+np.exp(-x))
print(sigmoid)

[-3.         -2.87755102 -2.75510204 -2.63265306 -2.51020408 -2.3877551
 -2.26530612 -2.14285714 -2.02040816 -1.89795918 -1.7755102  -1.65306122
 -1.53061224 -1.40816327 -1.28571429 -1.16326531 -1.04081633 -0.91836735
 -0.79591837 -0.67346939 -0.55102041 -0.42857143 -0.30612245 -0.18367347
 -0.06122449  0.06122449  0.18367347  0.30612245  0.42857143  0.55102041
  0.67346939  0.79591837  0.91836735  1.04081633  1.16326531  1.28571429
  1.40816327  1.53061224  1.65306122  1.7755102   1.89795918  2.02040816
  2.14285714  2.26530612  2.3877551   2.51020408  2.63265306  2.75510204
  2.87755102  3.        ]
[0.04742587 0.05327452 0.05979915 0.06706626 0.07514592 0.08411121
 0.09403734 0.10500059 0.11707679 0.13033963 0.14485842 0.16069565
 0.17790412 0.19652392 0.2165791  0.23807447 0.26099251 0.28529068
 0.3108993  0.33772042 0.3656277  0.39446751 0.42406149 0.45421029
 0.48469866 0.51530134 0.54578971 0.57593851 0.60553249 0.6343723
 0.66227958 0.6891007  0.71470932 0.73900749 0.76192553 0

In [24]:
matrix2=np.random.randint(1,100,(4,4))
secondm=matrix2[:,1]
print(matrix2)
print(secondm)
dig=np.diag(matrix2)
print(dig)
odd=matrix2[matrix2%2==1]
print(odd)


[[16  8 99 82]
 [62 93 79 82]
 [47 76 60 60]
 [ 7  8 83 22]]
[ 8 93 76  8]
[16 93 60 22]
[99 93 79 47  7 83]


In [28]:
normal=np.random.normal(loc=50,scale=15,size=1000)
print(normal)
clip=np.clip(normal,0,100)
print("next")
print(clip)

[47.53411442 34.31721632 42.04529129 34.95158202 34.04583785 49.45716366
 25.74874236 69.2512207  63.93202903 41.10192764 35.61640625 29.86099322
 52.47341897 74.53851814 70.11259005 77.6270121  19.97880817 55.54400248
 41.83574423 36.19852714 56.22066036 41.04871139 52.69991036 49.10066852
 33.31820499 37.75671661 57.30356696 54.63992867 45.34628372 77.84848632
 50.16941692 67.14269315 64.11019785 36.60529823 64.70730517 44.40407302
 46.67960306 34.21507493 63.00334613 45.7333695  65.30565021 50.67581358
 36.71987783 34.3104808  26.79477069 48.39945276 58.57315004 33.57678505
 -4.62630024 33.18940691 49.55229603 62.44802573 26.8572383  52.93928019
 69.40169278 61.087966   49.72595013 59.30985518 89.30057332 40.83272033
 59.56714463 53.85756604 43.34382045 52.98549743 68.10079187 34.19556047
 72.38123703 13.30065929 48.70733993 63.01300791 19.87601781 51.62596584
 33.07483529 65.66215303 45.33047804 31.516865   60.36664116 53.21242139
 59.83589609 41.43204863 30.34462744 70.94587914 66